services:
  - type: web
    name: lucky-bingo-v6
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 30 --timeout 120 --keep-alive 65
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: BINGO_VOICE
        value: fil-PH-AngeloNeural
